# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 36093fe3252255fdca006f484f38c3c5c23685fd7b84b28140701f02b4a7eccb373ca9eee55d1df1e05fd73e48361f87c7738c23950c100a6d153deb096781d1

test:
  domain_name: example.com 
  secret_key_base: d4c90212b6429d6e06e79dccdf731892b3473745fb998a6b944d8326ad458d5877fb69599eae2e99f0f19e295fae3dbbca3cedd0221eb32334cdae27d758d30b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
